config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :accounts
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :account_entries
end

app/models/account_entry.rb
class AccountEntry < ApplicationRecord
  belongs_to :account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < Account
  has_many :time_entries
end

app/models/employee.rb
class Employee < Account
  has_many :time_entries
    has_and_belongs_to_many :projects, join_table: "employees_projects"


  def total_hours
    time_entries.sum(:time)
  end

  def log_time(amount, customer)
    TimeEntry.create(time: amount, employee: self, account: customer)
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :customer
  has_and_belongs_to_many :employees, join_table: "employees_projects"
end

app/models/time_entry.rb
class TimeEntry < AccountEntry
  belongs_to :employee
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<table>
  <% @accounts.each do |account| %>
  <tr>
    <td><%= link_to account.name, account_path(account) %></td>
    <td><%= account.type.to_s %></td>
  </tr>
  <% end %>
</table>

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>



<% if @ccount.is_a?(Employee) %>
  <h3>Time Entries</h3>
  <table>
    <% @account.time_entries.each do |entry| %>
    <tr>
      <td><%= entry.inspect %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <h3>Account Entries</h3>
  <table>
    <% @account.account_entries.each do |entry| %>
    <tr>
      <td><%= entry.inspect %></td>
    </tr>
    <% end %>
  </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biller</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>